###########################################################
#
#  SensorDaemon Configuration File                           
#         
###########################################################

##### Settings #####

seakeeper_system_all = 26

# delay time
timeout = 20000
