###########################################################
#
#  SensorDaemon Configuration File                           
#         
###########################################################

##### Settings #####

port = 26

host_name = 20000
