###########################################################
#
#  SensorDaemon Configuration File                           
#         
###########################################################

##### Settings #####

port = 26

# delay time
host_name = 20000
