###########################################################
#
#  SensorDaemon Configuration File                           
#         
###########################################################

##### Settings #####

# Port for server operation
port = 555

# Host name for server operation
host_name = "localhost"
port = 8080;
ip = "0.0.0.0";
host_name = "localhost";