###########################################################
#
#  SensorDaemon Configuration File                           
#         
###########################################################

##### Settings #####

# Port for server operation
port = 5173

# Host name for server operation
ip = 0.0.0.0

# ls -of open file -i :5183
