###########################################################
#
#  SensorDaemon Configuration File                           
#         
###########################################################

##### Settings #####

# Port for server operation
port = 5173;

# Host name for server operation
host_name = "localhost"

ip = "127.0.0.0";
